print(dir(str))
# print('Int: ')
# print(dir(int))
# print('Float: ')
# print(dir(float))
# print('Bool: ')
# print(dir(bool))
# print('Range: ')
# print(dir(range))
# print('List: ')
# print(dir(list))
# print('Set: ')
# print(dir(set))
# print('Dict: ')
# print(dir(dict))
# print('Tuple: ')
# print(dir(tuple))
